theme: jekyll-theme-tactile
title: Owen Young
description: University of Michigan class of 2024
description: BS in Computer Science
description: Minor in Japanese Language 
#github:
#  is_project_page: false
