theme: jekyll-theme-tactile
title: Owen Young
layout: default
description1: University of Michigan Class of 2024
description2: BS in Computer Science
description3: Minor in Japanese Language
#github:
#  is_project_page: false
