theme: jekyll-theme-tactile
title: Owen Young
layout: none
#description: "University of Michigan class of 2024\n\n\nBS in Computer Science\n\n\nMinor in Japanese Language\n"
#github:
#  is_project_page: false
